<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="DESKTOP-IR55ORM" failures="1" tests="1" name="Test(failed)" time="9.385" errors="0" timestamp="2025-02-21T16:07:30 IST">
  <testcase classname="testCases.TC003_LoginDDT" name="verifylogInDDT" time="0.0">
    <failure type="java.lang.RuntimeException" message="java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3">
      <![CDATA[java.lang.RuntimeException: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
at utilities.DataProviders.getdata(DataProviders.java:29)
... 25 more
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- verifylogInDDT -->
  <testcase classname="testCases.TC003_LoginDDT" name="set" time="0.0">
    <ignored/>
  </testcase> <!-- set -->
</testsuite> <!-- Test(failed) -->
